additional:
  # temporarily include repos manually # https://github.com/github/docs/issues/3630
  - "docker-*"

files:
  - "!.env"
  - "!**/publish-matrix.json"
  - "!**/template-sync.yml"
  - "!colophon.yml"
  - "!Dockerfile"
  - "!docs/README.md"
  - "!README.md"
  - "!src/.gitignore"
  - "!.github/dependabot.yml"
  - .github/dependabot-template.yml: .github/dependabot.yml
