additional:
  # temporarily include repos manually # https://github.com/github/docs/issues/3630
  - "docker-*"

files:
  - "!.env"
  - "!**/matrix-*.json"
  - "!**/template-sync.yml"
  - "!colophon.yml"
  - "!Dockerfile"
  - "!docs/README.md"
  - "!README.md"
  - "!src/.gitignore"
  - "!.github/dependabot.yml"
  - "!.github/workflows/*.yml"
  - .github/template/push.yml: .github/workflows/push.yml
  - .github/template/readme.yml: .github/workflows/readme.yml
  - .github/template/pull_request_target.yml: .github/workflows/pull_request_target.yml
  - .github/template/dependabot.yml: .github/dependabot.yml
